Repository univCabi/BE_Spring, pull requests merged in 2025-03, with the labels that each got.

#3 Git Templates , Redis , MySQL 세팅 추가
  .github/ISSUE_TEMPLATE/ISSU_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  build.gradle
  src/main/java/org/univcabi/univcabi/configs/RedisConfig.java
  src/main/resources/application.properties
Labels: Feat, Docs

#5 Login API Test Logic 구현
  src/main/java/org/univcabi/univcabi/UnivCabiApplication.java
  src/main/java/org/univcabi/univcabi/auth/controller/AuthnController.java
  src/main/java/org/univcabi/univcabi/auth/dto/AuthnRequestDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/AuthnResponseDto.java
  src/main/java/org/univcabi/univcabi/auth/entity/Authn.java
  src/main/java/org/univcabi/univcabi/auth/entity/AuthnRole.java
  src/main/java/org/univcabi/univcabi/auth/repository/AuthnRepository.java
  src/main/java/org/univcabi/univcabi/auth/service/AuthnService.java
  src/main/java/org/univcabi/univcabi/configs/SecurityConfig.java
Labels: Feat

#7 Fix:같은 name 값을 가진 issue 생성 템플릿 수정
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/이슈생성-템플릿.md
Labels: bug

#9 로그인 로그아웃 로직 with Cookie in JWT
  build.gradle
  src/main/java/org/univcabi/univcabi/UnivCabiApplication.java
  src/main/java/org/univcabi/univcabi/auth/controller/AuthnController.java
  src/main/java/org/univcabi/univcabi/auth/controller/TokenController.java
  src/main/java/org/univcabi/univcabi/auth/dto/AuthnRequestDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/AuthnResponseDto.java
  src/main/java/org/univcabi/univcabi/auth/security/CustomUserDetailsService.java
  src/main/java/org/univcabi/univcabi/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/univcabi/univcabi/auth/security/JwtTokenProvider.java
  src/main/java/org/univcabi/univcabi/auth/service/AuthnService.java
  src/main/java/org/univcabi/univcabi/auth/service/TokenService.java
  src/main/java/org/univcabi/univcabi/configs/SecurityConfig.java
  src/main/resources/application.properties
  src/test/java/org/univcabi/univcabi/auth/security/JwtTokenProviderTest.java
Labels: Feat

#12 프로젝트 구조 세팅(MVC) 및 테스트용 mock data 추가
  build.gradle
  src/main/java/org/univcabi/univcabi/auth/entity/Authn.java
  src/main/java/org/univcabi/univcabi/auth/service/AuthnService.java
  src/main/java/org/univcabi/univcabi/cabinet/controller/CabinetController.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetFindAllInfoRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetFindOneInfoRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetHistoryRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetRentRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetReturnRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetSearchDetailRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/request/CabinetSearchRequestDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetDetailResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetFindAllInfoResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetHistoryResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetInfoResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetPageResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetSearchDetailResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/dto/response/CabinetSearchResponseDto.java
  src/main/java/org/univcabi/univcabi/cabinet/entity/Building.java
  src/main/java/org/univcabi/univcabi/cabinet/entity/BuildingName.java
  src/main/java/org/univcabi/univcabi/cabinet/entity/Cabinet.java
  src/main/java/org/univcabi/univcabi/cabinet/entity/CabinetHistory.java
  src/main/java/org/univcabi/univcabi/cabinet/entity/CabinetPosition.java
  src/main/java/org/univcabi/univcabi/cabinet/entity/CabinetStatus.java
  src/main/java/org/univcabi/univcabi/cabinet/repository/CabinetCustomRepository.java
  src/main/java/org/univcabi/univcabi/cabinet/repository/CabinetCustomRepositoryImpl.java
  src/main/java/org/univcabi/univcabi/cabinet/repository/CabinetRepository.java
  src/main/java/org/univcabi/univcabi/cabinet/service/CabinetService.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetDetailVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetFindOneVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetHistoryResponseVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetHistoryVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetPageResponseVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetPageVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetRentVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetReturnVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetSearchDetailVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetSearchVo.java
  src/main/java/org/univcabi/univcabi/cabinet/vo/CabinetVo.java
  src/main/java/org/univcabi/univcabi/configs/QueryDslConfig.java
  src/main/java/org/univcabi/univcabi/configs/SecurityConfig.java
  src/main/java/org/univcabi/univcabi/user/entity/User.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Flush_all_data.sql
  src/main/resources/db/migration/V2__Insert_building_data.sql
  src/main/resources/db/migration/V3__Insert_user_data.sql
  src/main/resources/db/migration/V4__Insert_authn_data.sql
  src/main/resources/db/migration/V5__Insert_cabinet_data.sql
  src/main/resources/db/migration/V6__Insert_cabinet_position_data.sql
  src/main/resources/db/migration/V7__Insert_playable_data.sql
Labels: Feat, Fix, Refactor, Test, Build

#15 authn API 프로젝트 구조 개선
  .gitignore
  src/main/java/org/univcabi/univcabi/auth/controller/AuthnController.java
  src/main/java/org/univcabi/univcabi/auth/controller/TokenController.java
  src/main/java/org/univcabi/univcabi/auth/dto/AuthnRequestDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/AuthnResponseDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/request/AuthnCreateRequestDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/request/AuthnDeleteRequestDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/request/AuthnLoginRequestDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/response/AuthnCreateResponseDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/response/AuthnDeleteResponseDto.java
  src/main/java/org/univcabi/univcabi/auth/dto/response/AuthnLoginResponseDto.java
  src/main/java/org/univcabi/univcabi/auth/entity/Authn.java
  src/main/java/org/univcabi/univcabi/auth/repository/AuthnRepository.java
  src/main/java/org/univcabi/univcabi/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/univcabi/univcabi/auth/security/JwtTokenProvider.java
  src/main/java/org/univcabi/univcabi/auth/service/AuthnService.java
  src/main/java/org/univcabi/univcabi/auth/vo/AuthnCreateVo.java
  src/main/java/org/univcabi/univcabi/auth/vo/AuthnDeleteVo.java
  src/main/java/org/univcabi/univcabi/auth/vo/AuthnLoginVo.java
  src/main/java/org/univcabi/univcabi/auth/vo/AuthnTokenGenerateVo.java
  src/main/java/org/univcabi/univcabi/configs/SecurityConfig.java
  src/main/resources/db/migration/V7__Insert_playable_data.sql
  src/test/java/org/univcabi/univcabi/auth/security/JwtTokenProviderTest.java
Labels: Feat, Refactor
